"""Render manuscript-ready figures from the v0.4 multi-seed ICg-Bench artifacts.

Consumes ``outputs/bottleneck_v0_5/{summary.csv, per_seed.csv, per_state_recovery_r2.csv,
intervention_conformity__*.csv}`` and writes four figures to
``outputs/figures/`` as 300 DPI PNGs:

- ``fig_responsive_conformity.png`` : headline bar (responsive_dgp_conformity by cohort × variant).
- ``fig_auroc_vs_conformity.png``   : scatter of AUROC against responsive_dgp_conformity.
- ``fig_recovery_r2_heatmap.png``   : per-state recovery R^2 across cohorts (averaged over seeds).
- ``fig_intervention_deltas.png``   : grid of per-intervention mean risk deltas, faceted by cohort.

If ``per_state_recovery_r2.csv`` is missing it is regenerated by re-fitting stage 1
of each cohort × seed in turn (≈ 60 seconds for the full v0.4 sweep).
"""

from __future__ import annotations

import argparse
import sys
import warnings
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from icg_cast.io import ensure_dir  # noqa: E402

DEFAULT_V0_DIR = REPO_ROOT / "outputs" / "bottleneck_v0_5"
DEFAULT_FIGDIR = REPO_ROOT / "outputs" / "figures"
V0_DIR = DEFAULT_V0_DIR
FIGDIR = DEFAULT_FIGDIR

matplotlib.use("Agg")
plt.rcParams.update({
    "figure.dpi": 110,
    "savefig.dpi": 300,
    "font.size": 10,
    "axes.titlesize": 11,
    "axes.labelsize": 10,
    "legend.fontsize": 9,
    "axes.grid": True,
    "grid.alpha": 0.25,
})

COHORT_ORDER: list[str] = [
    "linear_lowhet",
    "nonlinear_mixhost",
    "partial_observability",
    "nonlinear_obs",
    "misspecified_signs",
    "misspecified_signs_v2",
]
VARIANT_ORDER: list[str] = ["v0_1", "sign_constrained", "sign_constrained_augmented"]
VARIANT_LABEL: dict[str, str] = {
    "v0_1":                       "v0.1 unconstrained",
    "sign_constrained":           "sign-constrained",
    "sign_constrained_augmented": "sign-constrained\n+ augmented",
}
VARIANT_COLOR: dict[str, str] = {
    "v0_1":                       "#6c7a89",
    "sign_constrained":           "#2c7fb8",
    "sign_constrained_augmented": "#d95f02",
}
COHORT_MARKER: dict[str, str] = {
    "linear_lowhet": "o", "nonlinear_mixhost": "s", "partial_observability": "D",
    "nonlinear_obs": "^", "misspecified_signs": "X", "misspecified_signs_v2": "P",
}


def _ensure_per_state_r2() -> pd.DataFrame:
    """Load (or regenerate) the per-state recovery R^2 long table."""
    csv = V0_DIR / "per_state_recovery_r2.csv"
    if csv.exists():
        return pd.read_csv(csv)

    from sklearn.model_selection import train_test_split

    from icg_cast.benchmark import generate
    from icg_cast.bottleneck import DEFAULT_BOTTLENECK_UNITS, MechanismBottleneckClassifier

    rows: list[dict[str, object]] = []
    for cohort in COHORT_ORDER:
        for seed in (7, 13, 31):
            df, _ = generate(cohort, n=1200, months=72, seed=seed)
            feat = [
                c for c in df.columns
                if c.startswith(("tx_", "epi_", "sig_activity_", "kcc", "host_"))
                or c in ("dose", "mut_total_count")
            ]
            bcols = [c for c in DEFAULT_BOTTLENECK_UNITS if c in df.columns]
            X = df[feat].copy()
            S = df[bcols].copy()
            y = df["future_cancer_transition_event"].astype(int).to_numpy()
            idx = np.arange(len(df))
            tr, te = train_test_split(idx, test_size=0.30, stratify=y, random_state=seed)
            mb = MechanismBottleneckClassifier(
                bottleneck_units=bcols, feature_columns=feat,
                stage2_kind="sign_constrained", random_state=seed,
            )
            mb.fit(X.iloc[tr].join(S.iloc[tr]), y[tr])
            rec = mb.score_recovery(X.iloc[te], S.iloc[te])
            for unit, r2 in zip(rec["bottleneck_unit"], rec["recovery_r2"].astype(float), strict=False):
                rows.append({"cohort": cohort, "variant": "sign_constrained", "seed": seed,
                             "bottleneck_unit": unit, "recovery_r2": float(r2)})
            print(f"  refit recovery R^2 for {cohort} seed={seed}: mean R^2 = {rec['recovery_r2'].mean():.3f}")
    out = pd.DataFrame(rows)
    try:
        out.to_csv(csv, index=False)
    except OSError as exc:
        warnings.warn(
            f"could not cache regenerated per-state R2 table at {csv}: {exc}",
            RuntimeWarning,
            stacklevel=2,
        )
    return out


def fig_responsive_conformity(summary: pd.DataFrame) -> None:
    fig, ax = plt.subplots(figsize=(11, 4.2))
    n_cohorts = len(COHORT_ORDER)
    n_variants = len(VARIANT_ORDER)
    width = 0.26
    x = np.arange(n_cohorts)
    for j, variant in enumerate(VARIANT_ORDER):
        sub = (summary[summary["variant"] == variant]
               .set_index("cohort").reindex(COHORT_ORDER))
        m = sub["responsive_dgp_conformity_mean"].to_numpy(dtype=float)
        s = sub["responsive_dgp_conformity_sd"].to_numpy(dtype=float)
        ax.bar(
            x + (j - (n_variants - 1) / 2) * width, m, width,
            yerr=s, capsize=3, color=VARIANT_COLOR[variant],
            label=VARIANT_LABEL[variant].replace("\n", " "),
            edgecolor="white", linewidth=0.6,
        )
    ax.axhline(1.0, color="black", lw=0.5, ls=":", alpha=0.5)
    ax.set_xticks(x)
    ax.set_xticklabels([c.replace("_", "\n") for c in COHORT_ORDER])
    ax.set_ylabel("Responsive DGP conformity\n(sign matches AND |Δ risk| ≥ 0.005)")
    ax.set_ylim(0.0, 1.05)
    ax.set_title("MB-CNet responsive intervention conformity across ICg-Bench cohorts (mean ± SD, n_seeds = 3)")
    ax.legend(loc="lower left", framealpha=0.95)
    fig.tight_layout()
    fig.savefig(FIGDIR / "fig_responsive_conformity.png", bbox_inches="tight")
    plt.close(fig)


def fig_auroc_vs_conformity(summary: pd.DataFrame) -> None:
    fig, ax = plt.subplots(figsize=(7.5, 5.2))
    for cohort in COHORT_ORDER:
        for variant in VARIANT_ORDER:
            row = summary[(summary["cohort"] == cohort) & (summary["variant"] == variant)]
            if row.empty:
                continue
            x = float(row["responsive_dgp_conformity_mean"].iloc[0])
            y = float(row["auroc_mean"].iloc[0])
            xs = float(row["responsive_dgp_conformity_sd"].iloc[0])
            ys = float(row["auroc_sd"].iloc[0])
            ax.errorbar(
                x, y, xerr=xs, yerr=ys, fmt=COHORT_MARKER[cohort],
                color=VARIANT_COLOR[variant], markersize=9,
                markeredgecolor="white", markeredgewidth=0.6, capsize=2, alpha=0.95,
            )
    ax.set_xlabel("Responsive DGP conformity")
    ax.set_ylabel("AUROC")
    ax.set_title("Predictive discrimination vs causal coherence (mean ± SD)")
    ax.set_xlim(0.0, 1.05)
    ax.set_ylim(0.75, 0.96)
    legend_vars = [plt.Line2D([0], [0], marker="o", color=VARIANT_COLOR[v], markersize=9,
                              linestyle="None", markeredgecolor="white",
                              label=VARIANT_LABEL[v].replace("\n", " "))
                   for v in VARIANT_ORDER]
    legend_cohorts = [plt.Line2D([0], [0], marker=COHORT_MARKER[c], color="black",
                                 markerfacecolor="none", markersize=9, linestyle="None",
                                 label=c)
                      for c in COHORT_ORDER]
    leg1 = ax.legend(handles=legend_vars, loc="upper left", title="MB-CNet variant", framealpha=0.95)
    ax.add_artist(leg1)
    ax.legend(handles=legend_cohorts, loc="lower right", title="cohort", framealpha=0.95)
    fig.tight_layout()
    fig.savefig(FIGDIR / "fig_auroc_vs_conformity.png", bbox_inches="tight")
    plt.close(fig)


def fig_recovery_r2_heatmap(per_state: pd.DataFrame) -> None:
    unit_order = [
        "state_final_DNA_adducts", "state_final_ROS", "state_final_inflammation",
        "state_final_epigenetic_age", "state_final_proliferation",
        "state_final_mutation_rate", "state_final_clone_fraction",
        "state_final_driver_count_proxy", "state_final_immune_clearance",
    ]
    pivot = (per_state.groupby(["cohort", "bottleneck_unit"])["recovery_r2"]
             .mean().reset_index()
             .pivot(index="cohort", columns="bottleneck_unit", values="recovery_r2")
             .reindex(index=COHORT_ORDER, columns=unit_order))
    fig, ax = plt.subplots(figsize=(10.5, 3.6))
    arr = pivot.to_numpy(dtype=float)
    im = ax.imshow(arr, vmin=0.5, vmax=1.0, cmap="viridis", aspect="auto")
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            v = arr[i, j]
            ax.text(j, i, f"{v:.2f}", ha="center", va="center",
                    color="white" if v < 0.85 else "black", fontsize=8)
    ax.set_xticks(np.arange(arr.shape[1]))
    ax.set_xticklabels([u.replace("state_final_", "") for u in unit_order],
                       rotation=30, ha="right")
    ax.set_yticks(np.arange(arr.shape[0]))
    ax.set_yticklabels(COHORT_ORDER)
    ax.set_title("Per-state stage-1 recovery R² (mean across seeds)")
    cbar = plt.colorbar(im, ax=ax, shrink=0.85, label="R²")
    cbar.ax.tick_params(labelsize=8)
    ax.grid(False)
    fig.tight_layout()
    fig.savefig(FIGDIR / "fig_recovery_r2_heatmap.png", bbox_inches="tight")
    plt.close(fig)


def fig_intervention_deltas() -> None:
    csvs = sorted(V0_DIR.glob("intervention_conformity__*.csv"))
    if not csvs:
        return
    rows = []
    for p in csvs:
        name = p.stem.replace("intervention_conformity__", "")
        cohort, variant, seed_tag = name.rsplit("__", 2)
        seed = int(seed_tag.replace("seed", ""))
        df = pd.read_csv(p)
        df["cohort"], df["variant"], df["seed"] = cohort, variant, seed
        rows.append(df)
    long = pd.concat(rows, ignore_index=True)

    interventions = list(long["intervention"].drop_duplicates())
    n_cohorts = len(COHORT_ORDER)
    fig, axes = plt.subplots(
        n_cohorts, 1, figsize=(11.5, 1.6 * n_cohorts + 1.5),
        sharex=True, sharey=False,
    )
    if n_cohorts == 1:
        axes = [axes]
    width = 0.26
    x = np.arange(len(interventions))
    for ax, cohort in zip(axes, COHORT_ORDER, strict=False):
        sub = long[long["cohort"] == cohort]
        for j, variant in enumerate(VARIANT_ORDER):
            ss = (sub[sub["variant"] == variant]
                  .groupby("intervention")["mean_risk_change"]
                  .agg(["mean", "std"]).reindex(interventions))
            ax.bar(
                x + (j - 1) * width, ss["mean"].to_numpy(dtype=float), width,
                yerr=ss["std"].to_numpy(dtype=float), capsize=2,
                color=VARIANT_COLOR[variant],
                label=VARIANT_LABEL[variant].replace("\n", " "),
                edgecolor="white", linewidth=0.4,
            )
        ax.axhline(0.0, color="black", lw=0.7, alpha=0.6)
        ax.set_ylabel(cohort, rotation=0, ha="right", va="center", fontsize=9)
        ax.grid(axis="y", alpha=0.25)
    axes[0].legend(loc="upper right", ncol=3, framealpha=0.95)
    axes[-1].set_xticks(x)
    axes[-1].set_xticklabels([i.replace("do_", "") for i in interventions],
                             rotation=22, ha="right")
    axes[-1].set_xlabel("intervention")
    fig.suptitle("Mean predicted-risk change per intervention (mean ± SD over seeds)", y=0.995)
    fig.tight_layout()
    fig.savefig(FIGDIR / "fig_intervention_deltas.png", bbox_inches="tight")
    plt.close(fig)


def _display_path(path: Path) -> Path:
    try:
        return path.relative_to(REPO_ROOT)
    except ValueError:
        return path


def main(argv: list[str] | None = None) -> None:
    global FIGDIR, V0_DIR

    parser = argparse.ArgumentParser(description="Render manuscript figures from ICg-Bench artifacts")
    parser.add_argument("--inputdir", type=Path, default=DEFAULT_V0_DIR)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_FIGDIR)
    args = parser.parse_args(argv)

    V0_DIR = args.inputdir
    FIGDIR = ensure_dir(args.outdir, fallback_prefix="icg-cast-figures-")
    summary_path = V0_DIR / "summary.csv"
    if not summary_path.exists():
        raise SystemExit(f"summary artifact not found: {summary_path}")

    summary = pd.read_csv(summary_path)
    per_state = _ensure_per_state_r2()

    fig_responsive_conformity(summary)
    fig_auroc_vs_conformity(summary)
    fig_recovery_r2_heatmap(per_state)
    fig_intervention_deltas()

    pngs = sorted(p.name for p in FIGDIR.glob("fig_*.png"))
    print(f"wrote {len(pngs)} figures under {_display_path(FIGDIR)}/:")
    for p in pngs:
        print(f"  - {p}")


if __name__ == "__main__":
    main()
